module.exports = {
    CommonInfo: {
        LibraryName: "",
        Description: "",
        Adress: "",
        LibPhone: "",
        Email: "",
        managerSurname: "",
        ManagerMiddleName: "",
        ManagerName: "",
        ManagerPhone: "",
        ManagerEmail: "",
        FundSize: "",
    }, Position: {
        BuildingSquare: "",
        BuildingYear: "",
        BuildingDistrict: "",
    }, Staff: {
        StaffSize: "",
    }, GosRegister: {
        StateRegisterCertificate: "",
    }, Specialisation: {
        Specialization: "",
    }, ReadingHall: {
        CityDistrict: "",
        HallAvailable: "",
        ReadingHallAvilable: "",
        ReadingHallSquare: "",
        ReadingHallStoreSquare: "",
        ReadingHallFundCount: "",
    }, IsAbonement: {
        Abonement: "",
        AbonementSquare: "",
        AbonementFundSquare: "",
        AbonementFundCount: "",
    }, Fund: {
        FundDepartment: "",
        FundDepartmentSquare: "",
        FundSquare: "",
        FundCount: "",
        FundClosed: "",
        FundClosedSquare: "",
        FundClosedStoreSquare: "",
        FundClosedDocsCount: "",
    }, Computers: {
        ComputersCount: "",
        ComputersDigitalResAccess: "",
        ComputersInternetAccess: "",
    }, IsSpecialFund: {
        SpecialFund: "",
    }, Outdoor: {
        OutdoorMaintenance: "",
        HomeServiceLowMobility: "",
        LowMobilityCount: "",
    }, Disabled: {
        EasyTerritoryEnter: "",
        DisabledParking: "",
        DisabledOutStairs: "",
        OutdoorStairsHandrails: "",
        OutdoorRamp: "",
        OutdoorRampHandrails: "",
        EntranceDoor: "",
        IndoorStairs: "",
        IndoorStairsHandrails: "",
        DoorsWidth: "",
        IndoorObstacles: "",
        Lift: "",
        Escalator: "",
        LiftingPlatform: "",
        DisabledEvacuations: "",
        DisabledZone: "",
        DisabledPlumbing: "",
        TactileInformationFacilities: "",
        AcousticInformationFacilities: "",
        VisualInformationFacilities: "",
        AddLightsForDisabled: "",
        ServiceAccessibilityForDisabled: "",
        BrailleLiterature: "",
    }, Opening: {
        OpeningMonday: "",
        OpeningTuesday: "",
        OpeningWednesday: "",
        OpeningThursday: "",
        OpeningFriday: "",
        OpeningSaturday: "",
        OpeningSunday: "",
        SanitaryDay: "",
    }, ForVisitors: {
        CompsForVisitors: "",
        WiFiVisitors: "",
        Food: "",
        Parking: "",
    },  BuildingInfo: {
        BuildingType: "",
        BuildingConstructive: "",
        BuildingFloors: "",
        BuildingRoof: "",
        BuildingRoofMaterial: "",
        BuildingIsMonument: "",
        BuildingUsefullSquare: "",
        BuildingCategory: "",
        BuildingRenovationYear: "",
        BuildingNotUsefullSquare: "",
        BuildingRoomsCountBTI: "",
        BuildingRoomsUstavCount: "",
        BuildingFloorsUsing: "",
        BuildingStatus: "",
        BuildingBasement: "",
        BuildingSeparateInput: "",
        BuildingElectricity: "",
    }, Airing: {
        BuildingAiring: "",
        BuildingAiringCondition: "",
        BuildingConditioner: "",
        BuildingComunalServicesContracts: "",
        BuildingEngineerContracts: "",
    }, HeatWaterPreparation: {
        SystemsWashing: "",
        SystemsRepair: "",
        SystemsAdjustment: "",
        SystemHydraulicTest: "",
        SystemReadyAct: "",
        SystemOtherWork: "",
    }, WinterWorks: {
        WinterClearingWaterRoof: "",
        WinterClearingRoof: "",
        WinterLoftWarming: "",
        WinterHeatingRoofGutters: "",
        WinterLoftHearingWindows: "",
        WinterWindowsWarming: "",
        WinterBalconyDoorsWarming: "",
        WinterEntryDoors: "",
        WinterIsolationElectricWires: "",
        WinterFixHeatCurtains: "",
        WinterOther: "",
    }, AdjTerritory: {
        AdjacentTerritoryAvailability: ""
    }

};