module.exports = {
    ID: "ID",
    LibraryName: "Название",
    Description: "Описание",
    Adress: "Адрес",
    LibPhone: "Телефон библиотеки",
    Email: "Веб-сайт",
    managerSurname: "Фамилия заведующей",
    ManagerMiddleName: "Отчество",
    ManagerName: "Имя",
    ManagerPhone: "Телефон руководителя",
    ManagerEmail: "Почта руководителя",
    FundSize: "Размер фонда",
    BuildingSquare: "Площадь",
    BuildingYear: "Год постройки",
    BuildingDistrict: "Район",
    StaffSize: "Штат сотрудников",
    StateRegisterCertificate: "Свидетельство о государственно регистрации права",
    Specialization: "Специализация",
    CityDistrict: "Округ",
    HallAvailable: "Наличие зала",
    ReadingHallAvilable: "Имеется ли читальный зал",
    ReadingHallSquare: "Общая площадь читального зала",
    ReadingHallStoreSquare: "Площадь для хранения фонда в читальном зале",
    ReadingHallFundCount: "Кол-во фонда в читальном зале",
    Abonement: "Имеется ли абонемент",
    AbonementSquare: "Общая площадь абонемента",
    AbonementFundSquare: "Площадь для хранения фонда в абонементе",
    AbonementFundCount: "Кол-во фонда в абонементе",
    FundDepartment: "Наличие отдела, где располагается фонд",
    FundDepartmentName: "Название отдела",
    FundDepartmentSquare: "Общая площадь",
    FundSquare: "Площадь для хранения фонда",
    FundCount: "Кол-во фонд",
    FundClosed: "Имеется ли фонд с закрытым доступом для посетителей",
    FundClosedSquare: "Площадь помещения с закрытым доступом для посетителей",
    FundClosedStoreSquare: "Площадь для хранения фонда с закрытым доступом для посетителей",
    FundClosedDocsCount: "Общее количество документов в фонде с закрытым доступом",
    FundClosedWhat: "Что хранится в фонде закрытого доступа",
    FundClosedRoomType: "Вид помещения",
    FundClosedWhoAccess: "Кто имеет доступ",
    ComputersCount: "Всего в помещении",
    ComputersDigitalResAccess: "Из них компьютеризированных с возможностью доступа к электронным ресурсам",
    ComputersInternetAccess: "Из общего числа с возможностью выхода в интернет",
    SpecialFund: "Имеется ли специальный фонд",
    OutdoorMaintenance: "Внестационарное обслуживание",
    HomeServiceLowMobility: "Осуществляется ли обслуживание маломобильных граждан на дому",
    LowMobilityCount: "Кол-во обслуживаемых маломобильных граждан на дому",
    EasyTerritoryEnter: "Беспрепятственный вход на территорию",
    DisabledParking: "Парковочные места для инвалидов",
    DisabledOutStairs: "Наружная лестница",
    OutdoorStairsHandrails: "Поручни для наружной лестницы",
    OutdoorRamp: "Наружный пандус",
    OutdoorRampHandrails: "Поручни для наружного пандуса",
    EntranceDoor: "Входная дверь в здание",
    IndoorStairs: "Внутренние лестницы",
    IndoorStairsHandrails: "Поручни для внутренних лестниц",
    DoorsWidth: "Ширина дверных проемов",
    IndoorObstacles: "Препятствия внутри помещний",
    Lift: "Лифт",
    Escalator: "Эскалатор",
    LiftingPlatform: "Подъемная платформа",
    DisabledEvacuations: "Пути эвакуации для инвалидов",
    DisabledZone: "Специальная непроходная зона для размещения инвалидов",
    DisabledPlumbing: "Доступность сантехнического оборудования для инвалидов",
    TactileInformationFacilities: "Тактильные средства информации",
    AcousticInformationFacilities: "Акустические средства информации",
    VisualInformationFacilities: "Визуальные средства информации",
    AddLightsForDisabled: "Дополнительные источники света для инвалидов",
    ServiceAccessibilityForDisabled: "Доступность предоставляемых услуг для инвалидов",
    BrailleLiterature: "Наличие литературы со шрифтом Брайля",
    OpeningMonday: "Понедельник",
    OpeningTuesday: "Вторник",
    OpeningWednesday: "Среда",
    OpeningThursday: "Четверг",
    OpeningFriday: "Пятница",
    OpeningSaturday: "Суббота",
    OpeningSunday: "Воскресенье",
    SanitaryDay: "Санитарный день",
    CompsForVisitors: "Компьютеры для посетителей",
    WiFiVisitors: "WiFi для посетителей",
    Food: "Организация питания",
    Parking: "Наличие парковки",
    BuildingType: "Тип",
    BuildingConstructive: "Конструктив здания",
    BuildingFloors: "Количество этажей здания",
    BuildingRoof: "Тип кровли здания",
    BuildingRoofMaterial: "Материал кровли",
    BuildingIsMonument: "Является ли памятников архитектуры/Объектом культурного наследия",
    BuildingUsefullSquare: "Полезная площадь",
    BuildingCategory: "Категория помещения",
    BuildingRenovationYear: "Период проведения последнего капитального ремонта",
    BuildingNotUsefullSquare: "Площадь, используемая не по назначению ",
    BuildingRoomsCountBTI: "Общее количество помещений по плану БТИ",
    BuildingRoomsUstavCount: "Количество помещений, приспособленных для ведения уставной деятельности",
    BuildingFloorsUsing: "Количество занимаемых этажей",
    BuildingStatus: "Состояние помещения",
    BuildingBasement: "Подвал",
    BuildingSeparateInput: "Наличие отдельного входа",
    BuildingElectricity: "Кол-во единовременно отпущенной электрической мощности",
    BuildingAiring: "Наличие системы вентиляции",
    BuildingAiringCondition: "Состояние системы вентиляции",
    BuildingConditioner: "Наличие системы централизованного кондиционирования",
    BuildingComunalServicesContracts: "Контракты на коммунальные услуги",
    BuildingEngineerContracts: "Контракты на обслуживание инженерных систем",
    SystemsWashing: "Промывка",
    SystemsRepair: "Ремонт и замена трубопроводов и оборудования",
    SystemsAdjustment: "Наладочно-регулировочные работы",
    SystemHydraulicTest: "Проведение гидравлических испытаний",
    SystemReadyAct: "Получение Акта готовности",
    SystemOtherWork: "Другие работы",
    WinterClearingWaterRoof: "Очистка системы водостока кровли",
    WinterClearingRoof: "Очистка кровли",
    WinterLoftWarming: "Утепление чердаков и подвалов",
    WinterHeatingRoofGutters: "Обслуживание системы электрообогрева желобов водостока крыши",
    WinterLoftHearingWindows: "Обслуживание и утепление слуховых окон чердака",
    WinterWindowsWarming: "Утепление окон",
    WinterBalconyDoorsWarming: "Утепление балконных дверей",
    WinterEntryDoors: "Утепление входных дверей, настройка доводчиков",
    WinterIsolationElectricWires: "Проверка сопротивления изоляции электропроводки и электрооборудования",
    WinterFixHeatCurtains: "Обслуживание тепловых завес и калориферов",
    WinterOther: "Другие работы",
    AdjacentTerritoryAvailability: "Наличие прилегающей территории",

    CommonInfo: "Общая информация",
    Position: "Местоположение",
    Staff: "Персонал",
    GosRegister: "Государственная регистрация",
    Specialisation: "Специализация",
    ReadingHall: "Читательский зал",
    IsAbonement: "Абонемент",
    Fund: "Фонд",
    Computers: "Коспьютеризация",
    IsSpecialFund: "Специальный фонд",
    Outdoor: "Внестационар",
    Disabled: "Для посетителей с ограниченными возможностями",
    Opening: "Время работы",
    ForVisitors: "Услуги для посетителей",
    BuildingInfo: "Информация о здании",
    Airing: "Вентиляция и контракты",
    HeatWaterPreparation: "Обслуживание инженерных систем",
    WinterWorks: "Работы по подготовке к зиме",
    AdjTerritory: "Прилегающая территория"
};